using EPM.Domain.Abstractions;

namespace EPM.Domain.Identity;

/// <summary>
/// A long-lived credential that buys a new access token without re-entering a password.
/// Part of the <see cref="AppUser"/> aggregate — created and revoked through the user.
/// </summary>
public sealed class RefreshToken : Entity
{
    private RefreshToken()
    {
    }

    public int UserId { get; private set; }

    /// <summary>Opaque random string; generated by infrastructure, never derived from user data.</summary>
    public string Token { get; private set; } = null!;

    public DateTime ExpiresAtUtc { get; private set; }

    public DateTime CreatedAtUtc { get; private set; }

    public DateTime? RevokedAtUtc { get; private set; }

    internal static RefreshToken Issue(string token, DateTime expiresAtUtc, DateTime utcNow) =>
        new()
        {
            Token = token,
            ExpiresAtUtc = expiresAtUtc,
            CreatedAtUtc = utcNow,
        };

    public bool IsUsable(DateTime utcNow) => RevokedAtUtc is null && ExpiresAtUtc > utcNow;

    // Revocation is recorded rather than deleted: a rotated token that shows up again is a
    // signal worth being able to see.
    internal void Revoke(DateTime utcNow) => RevokedAtUtc ??= utcNow;
}
